application: danielcswainportfolio
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
# Static JS files.
- url: /static/js
  static_dir: static/js

# Static CSS files.
- url: /static/css
  static_dir: static/css

# Static Img files.
- url: /static/img
  static_dir: static/img

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
